import 'leads_models.dart';

/// Static mock database of leads used to populate the CRM Leads tab.
const List<Lead> mockLeads = [
  Lead(
    id: '1',
    name: 'Rahul Menon',
    status: 'Interested',
    source: 'New Admission',
    category: 'Hot',
    phone: '9876543210',
    location: 'Kochi',
  ),
  Lead(
    id: '2',
    name: 'Sneha Pillai',
    status: 'Follow Up',
    source: 'Enquiry',
    category: 'Warm',
    phone: '9876543211',
    location: 'Trivandrum',
  ),
  Lead(
    id: '3',
    name: 'Aravind Krishnan',
    status: 'Qualified',
    source: 'New Admission',
    category: 'Hot',
    phone: '9876543212',
    location: 'Calicut',
  ),
  Lead(
    id: '4',
    name: 'Divya Raveendran',
    status: 'New',
    source: 'Demo Request',
    category: 'Cold',
    phone: '9876543213',
    location: 'Kochi',
  ),
  Lead(
    id: '5',
    name: 'Mohammed Anas',
    status: 'Not Interested',
    source: 'Enquiry',
    category: 'Cold',
    phone: '9876543214',
    location: 'Thrissur',
  ),
  Lead(
    id: '6',
    name: 'Anjali Suresh',
    status: 'Interested',
    source: 'New Admission',
    category: 'Warm',
    phone: '9876543215',
    location: 'Palakkad',
  ),
  Lead(
    id: '7',
    name: 'Vishnu Prasad',
    status: 'Interested',
    source: 'Demo Request',
    category: 'Hot',
    phone: '9876543216',
    location: 'Kottayam',
  ),
  Lead(
    id: '8',
    name: 'Priya Nair',
    status: 'Qualified',
    source: 'Enquiry',
    category: 'Warm',
    phone: '9876543217',
    location: 'Kollam',
  ),
  Lead(
    id: '9',
    name: 'Sandeep Kumar',
    status: 'New',
    source: 'New Admission',
    category: 'Warm',
    phone: '9876543218',
    location: 'Kannur',
  ),
  Lead(
    id: '10',
    name: 'Gautham Krishna',
    status: 'Interested',
    source: 'Enquiry',
    category: 'Hot',
    phone: '9876543219',
    location: 'Alappuzha',
  ),
];
